//! The cache catalog — the heart of the app.
//!
//! Each entry describes a known cache pattern, its tier (1=safe, 2=confirm,
//! 3=user-call), what app owns it (so we can refuse to clean while open), and
//! the human explanation that shows in the UI.
//!
//! Adding a category = one entry in this file. No new Rust code anywhere else.
//!
//! Path knowledge for the developer-tool and app-cache categories was informed
//! by the Mole project (github.com/tw93/Mole, MIT licensed). Disk Doctor
//! reimplements the catalog as native Rust data — no code was copied.

use once_cell::sync::Lazy;
use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize, PartialEq, Eq)]
pub enum CleanMethod {
    /// Plain recursive remove. Used for cache dirs we definitely own.
    Recursive,
    /// Move to system Trash via the `trash` crate. Safer; reversible.
    Trash,
    /// Each found path is wiped via Trash. Used for scan-many-find-many cases
    /// (e.g. node_modules across many projects).
    TrashAll,
}

#[derive(Clone, Debug, Serialize)]
pub struct CacheCategory {
    pub id: &'static str,
    pub label: &'static str,
    pub tier: u8,
    /// Globs relative to $HOME unless they start with '/'.
    pub paths: &'static [&'static str],
    /// Scan ceiling for walking — protects against runaway sizes.
    pub max_depth: Option<usize>,
    pub why: &'static str,
    pub regenerates: &'static str,
    /// Process name (lowercase substring) to block cleaning while running.
    pub running_check: Option<&'static str>,
    pub method: CleanMethod,
}

pub static CATALOG: Lazy<Vec<CacheCategory>> = Lazy::new(|| {
    use CleanMethod::*;
    vec![
        // ================================================================
        // PACKAGE MANAGERS & LANGUAGE CACHES — Tier 1
        // Pure download caches. Every one regenerates on next install.
        // ================================================================
        CacheCategory {
            id: "npm-cache",
            label: "npm package cache",
            tier: 1,
            paths: &[".npm/_cacache", ".npm/_npx"],
            max_depth: None,
            why: "Every npm package version you've ever installed, kept in case you reinstall it.",
            regenerates: "npm rebuilds the cache on next install.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "pnpm-store",
            label: "pnpm content-addressable store",
            tier: 1,
            paths: &["Library/pnpm/store", ".pnpm-store"],
            max_depth: None,
            why: "pnpm's global package store. Shared across every pnpm project.",
            regenerates: "pnpm refetches packages on next install.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "yarn-cache",
            label: "Yarn package cache",
            tier: 1,
            paths: &[".yarn/cache", "Library/Caches/Yarn"],
            max_depth: None,
            why: "Yarn's global package cache.",
            regenerates: "Yarn refetches on next install.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "bun-cache",
            label: "Bun install cache",
            tier: 1,
            paths: &[".bun/install/cache"],
            max_depth: None,
            why: "Bun's package install cache.",
            regenerates: "Bun refetches on next install.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "js-tooling-caches",
            label: "JS build-tool caches (Vite, webpack, Turbo, ESLint…)",
            tier: 1,
            paths: &[
                ".cache/vite",
                ".vite/cache",
                ".cache/webpack",
                ".turbo/cache",
                ".parcel-cache",
                ".cache/eslint",
                ".cache/prettier",
                ".cache/typescript",
                ".cache/node-gyp",
                ".node-gyp",
                ".cache/node/corepack",
            ],
            max_depth: None,
            why: "Incremental build caches for Vite, webpack, Turborepo, Parcel, ESLint, Prettier, tsc.",
            regenerates: "Each tool rebuilds its cache on the next run.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "pip-cache",
            label: "pip package cache",
            tier: 1,
            paths: &["Library/Caches/pip"],
            max_depth: None,
            why: "Python package wheels cache.",
            regenerates: "pip refetches on next install.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "python-tool-caches",
            label: "Python tool caches (uv, Poetry, mypy, Ruff, pytest)",
            tier: 1,
            paths: &[
                ".cache/uv",
                ".cache/poetry",
                "Library/Caches/pypoetry",
                ".cache/mypy",
                ".cache/ruff",
                ".pytest_cache",
                ".cache/pre-commit",
            ],
            max_depth: None,
            why: "Caches for uv, Poetry, mypy, Ruff, pytest and pre-commit.",
            regenerates: "Each tool rebuilds its cache on the next run.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "conda-pkgs",
            label: "Conda package cache",
            tier: 2,
            paths: &[
                ".conda/pkgs",
                "miniconda3/pkgs",
                "anaconda3/pkgs",
                "miniforge3/pkgs",
                "mambaforge/pkgs",
            ],
            max_depth: None,
            why: "Downloaded Conda packages across every Conda install.",
            regenerates: "Conda re-downloads packages when an environment needs them.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "cargo-cache",
            label: "Rust / Cargo registry cache",
            tier: 1,
            paths: &[".cargo/registry/cache", ".cargo/git", ".rustup/downloads"],
            max_depth: None,
            why: "Cargo's downloaded crate sources and git checkouts.",
            regenerates: "Cargo refetches crates on next build.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "go-cache",
            label: "Go build + module cache",
            tier: 1,
            paths: &["Library/Caches/go-build", "go/pkg/mod/cache"],
            max_depth: None,
            why: "Go's compiled-object cache and downloaded module zips.",
            regenerates: "Go rebuilds and refetches on next build.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "gradle-cache",
            label: "Gradle caches",
            tier: 2,
            paths: &[".gradle/caches", ".gradle/daemon", ".gradle/workers"],
            max_depth: None,
            why: "Gradle's dependency and build caches. Common in Android / JVM projects.",
            regenerates: "Gradle rebuilds on next build (first build will be slower).",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "maven-cache",
            label: "Maven local repository",
            tier: 2,
            paths: &[".m2/repository"],
            max_depth: None,
            why: "Maven's local repo of every Java dependency you've ever pulled.",
            regenerates: "Maven re-downloads dependencies — first build after will be slow.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "ruby-gems-cache",
            label: "Ruby gem + Bundler cache",
            tier: 1,
            paths: &[".gem/specs", ".bundle/cache"],
            max_depth: None,
            why: "Cached Ruby gem metadata and Bundler downloads.",
            regenerates: "Bundler refetches on next install.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "jvm-misc-caches",
            label: "Other JVM/lang caches (Composer, NuGet, sbt, Coursier)",
            tier: 1,
            paths: &[
                ".composer/cache",
                "Library/Caches/composer",
                ".nuget/packages",
                ".sbt/boot",
                ".ivy2/cache",
                ".cache/coursier",
            ],
            max_depth: None,
            why: "Package caches for PHP Composer, .NET NuGet, Scala sbt/Ivy/Coursier.",
            regenerates: "Each tool refetches on next install.",
            running_check: None,
            method: Recursive,
        },
        // ================================================================
        // AI / AGENT TOOLS
        // ================================================================
        CacheCategory {
            id: "claude-vm",
            label: "Claude Code agent VM disk",
            tier: 2,
            paths: &["Library/Application Support/Claude/vm_bundles/claudevm.bundle"],
            max_depth: None,
            why: "A full Linux virtual-machine disk image that Claude's agent SDK runs in.",
            regenerates: "Claude rebuilds it on next agent run (slow first launch, then fine).",
            running_check: Some("claude"),
            method: Recursive,
        },
        CacheCategory {
            id: "opencode-snapshots",
            label: "opencode session snapshots",
            tier: 1,
            paths: &[".local/share/opencode/snapshot", ".cache/opencode"],
            max_depth: None,
            why: "Full file-system snapshots per opencode session for rollback.",
            regenerates: "Recreated as new sessions run.",
            running_check: Some("opencode"),
            method: Recursive,
        },
        CacheCategory {
            id: "codex-archived",
            label: "Codex archived sessions + logs",
            tier: 1,
            paths: &[
                ".codex/archived_sessions",
                ".codex/logs_2.sqlite",
                ".codex/logs_2.sqlite-wal",
                ".cache/codex-runtimes",
            ],
            max_depth: None,
            why: "Old Codex CLI session archives, runtimes and a fat logs SQLite.",
            regenerates: "Codex writes new sessions/logs as you use it.",
            running_check: Some("codex"),
            method: Recursive,
        },
        CacheCategory {
            id: "agent-cli-versions",
            label: "Old agent-CLI versions (Claude, Cursor)",
            tier: 1,
            paths: &[
                ".local/share/claude/versions",
                ".local/share/cursor-agent/versions",
            ],
            max_depth: None,
            why: "Superseded versions of the Claude / Cursor command-line agents.",
            regenerates: "The current version stays; old ones are dead weight.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "ollama-models",
            label: "Ollama local models",
            tier: 2,
            paths: &[".ollama/models"],
            max_depth: None,
            why: "Local LLMs you downloaded — often several GB each.",
            regenerates: "`ollama pull <model>` re-downloads any you want back.",
            running_check: Some("ollama"),
            method: Recursive,
        },
        CacheCategory {
            id: "ml-model-caches",
            label: "ML model caches (Hugging Face, PyTorch, TensorFlow, W&B)",
            tier: 2,
            paths: &[
                ".cache/huggingface",
                ".cache/torch",
                ".cache/tensorflow",
                ".cache/wandb",
                ".lmstudio/models",
            ],
            max_depth: None,
            why: "Downloaded model weights and datasets. Frequently the single biggest hidden directory on an ML machine.",
            regenerates: "Frameworks re-download weights on next use.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "copilot-cache",
            label: "GitHub Copilot cache",
            tier: 1,
            paths: &[".copilot/pkg", "Library/Caches/copilot"],
            max_depth: None,
            why: "GitHub Copilot's downloaded package cache.",
            regenerates: "Copilot refetches as needed.",
            running_check: None,
            method: Recursive,
        },
        // ================================================================
        // XCODE & APPLE DEVELOPER
        // ================================================================
        CacheCategory {
            id: "xcode-derived",
            label: "Xcode DerivedData + Archives",
            tier: 1,
            paths: &[
                "Library/Developer/Xcode/DerivedData",
                "Library/Developer/Xcode/Archives",
            ],
            max_depth: None,
            why: "Xcode build artifacts and archived builds.",
            regenerates: "Regenerates on next build.",
            running_check: Some("xcode"),
            method: Recursive,
        },
        CacheCategory {
            id: "xcode-device-support",
            label: "Xcode device support files",
            tier: 1,
            paths: &[
                "Library/Developer/Xcode/iOS DeviceSupport",
                "Library/Developer/Xcode/watchOS DeviceSupport",
                "Library/Developer/Xcode/tvOS DeviceSupport",
            ],
            max_depth: None,
            why: "Per-OS-version symbol caches Xcode builds when you attach a device.",
            regenerates: "Rebuilt the next time you connect a device on that OS version.",
            running_check: Some("xcode"),
            method: Recursive,
        },
        CacheCategory {
            id: "xcode-simulators",
            label: "iOS Simulators",
            tier: 2,
            paths: &["Library/Developer/CoreSimulator/Devices"],
            max_depth: None,
            why: "Snapshots of simulated iPhones/iPads. Often unused.",
            regenerates: "Recreate via Xcode > Settings > Platforms.",
            running_check: Some("simulator"),
            method: Recursive,
        },
        CacheCategory {
            id: "quicklook-thumbnails",
            label: "QuickLook thumbnail cache",
            tier: 1,
            paths: &["Library/Caches/com.apple.QuickLook.thumbnailcache"],
            max_depth: None,
            why: "macOS's cached file-preview thumbnails.",
            regenerates: "Rebuilt automatically as you browse files.",
            running_check: None,
            method: Recursive,
        },
        // ================================================================
        // BROWSERS
        // ================================================================
        CacheCategory {
            id: "browser-caches",
            label: "Browser caches (Chrome, Brave, Dia, Edge, Firefox, Arc…)",
            tier: 1,
            paths: &[
                "Library/Caches/Google",
                "Library/Caches/BraveSoftware",
                "Library/Caches/Dia",
                "Library/Caches/com.apple.Safari",
                "Library/Caches/Microsoft Edge",
                "Library/Caches/Firefox",
                "Library/Caches/Chromium",
                "Library/Caches/company.thebrowser.Browser",
                "Library/Caches/Comet",
            ],
            max_depth: None,
            why: "Chromium- and Firefox-flavoured web caches. Distinct from your bookmarks, history and logins.",
            regenerates: "Refills as you browse.",
            running_check: None,
            method: Recursive,
        },
        // ================================================================
        // ELECTRON & DESKTOP-APP CACHES — Tier 2
        // ================================================================
        CacheCategory {
            id: "descript-partitions",
            label: "Descript Electron partitions",
            tier: 2,
            paths: &["Library/Application Support/Descript/Partitions"],
            max_depth: None,
            why: "Descript embeds a full Chromium per editor partition.",
            regenerates: "Rebuilds on next launch.",
            running_check: Some("descript"),
            method: Recursive,
        },
        CacheCategory {
            id: "electron-app-caches",
            label: "Electron app caches (Notion, Slack, Discord, Stremio)",
            tier: 2,
            paths: &[
                "Library/Application Support/Notion/Partitions",
                "Library/Application Support/Slack/Cache",
                "Library/Application Support/Slack/Service Worker",
                "Library/Application Support/discord/Cache",
                "Library/Application Support/stremio-server/stremio-cache",
            ],
            max_depth: None,
            why: "Electron apps each ship a Chromium and cache the web at 4K speed.",
            regenerates: "All rebuild on next app launch.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "code-editor-caches",
            label: "Code editor caches (VS Code, Cursor, Zed, JetBrains)",
            tier: 2,
            paths: &[
                "Library/Caches/com.microsoft.VSCode",
                "Library/Caches/Cursor",
                "Library/Caches/dev.zed.Zed",
                "Library/Caches/Zed",
                "Library/Caches/JetBrains",
                "Library/Logs/JetBrains",
            ],
            max_depth: None,
            why: "Editor caches and logs for VS Code, Cursor, Zed and JetBrains IDEs.",
            regenerates: "Each editor rebuilds its cache on next launch.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "creative-app-caches",
            label: "Creative app caches (Adobe, Figma, Sketch, DaVinci)",
            tier: 2,
            paths: &[
                "Library/Caches/Adobe",
                "Library/Caches/com.adobe.PremierePro",
                "Library/Caches/com.figma.Desktop",
                "Library/Caches/com.bohemiancoding.sketch3",
                "Library/Caches/com.blackmagic-design.DaVinciResolve",
            ],
            max_depth: None,
            why: "Media and render caches for Adobe apps, Figma, Sketch, DaVinci Resolve.",
            regenerates: "Each app rebuilds its cache as you work.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "api-tool-caches",
            label: "API / DB tool caches (Postman, Insomnia, TablePlus)",
            tier: 2,
            paths: &[
                "Library/Caches/com.postmanlabs.mac",
                "Library/Caches/com.konghq.insomnia",
                "Library/Caches/com.tinyapp.TablePlus",
                "Library/Caches/com.sequel-ace.sequel-ace",
                "Library/Caches/com.proxyman.NSProxy",
            ],
            max_depth: None,
            why: "Caches for Postman, Insomnia, TablePlus, Sequel Ace, Proxyman.",
            regenerates: "Each app rebuilds its cache on next launch.",
            running_check: None,
            method: Recursive,
        },
        // ================================================================
        // CONTAINERS & DEVOPS
        // ================================================================
        CacheCategory {
            id: "docker-cache",
            label: "Docker build cache",
            tier: 2,
            paths: &[".docker/buildx/cache"],
            max_depth: None,
            why: "Docker BuildKit / buildx layer cache.",
            regenerates: "Docker rebuilds layers on next build. (`docker system prune` does more.)",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "devops-caches",
            label: "DevOps tool caches (Terraform, Bazel, SonarLint)",
            tier: 1,
            paths: &[
                ".cache/terraform",
                ".terraform.d/plugin-cache",
                ".cache/bazel",
                ".sonar",
                ".cache/pre-commit",
            ],
            max_depth: None,
            why: "Provider, plugin and analysis caches for Terraform, Bazel, SonarLint.",
            regenerates: "Each tool refetches on next run.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "playwright-cache",
            label: "Playwright / Puppeteer browser binaries",
            tier: 1,
            paths: &[
                "Library/Caches/ms-playwright",
                "Library/Caches/ms-playwright-go",
                ".cache/puppeteer",
                ".cache/electron",
            ],
            max_depth: None,
            why: "Headless Chromium / Firefox / WebKit downloaded by Playwright, Puppeteer and Electron tooling.",
            regenerates: "Re-downloaded when you next install those deps.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "homebrew-cache",
            label: "Homebrew download cache",
            tier: 1,
            paths: &["Library/Caches/Homebrew"],
            max_depth: None,
            why: "Bottles and source tarballs Homebrew downloaded during installs.",
            regenerates: "Homebrew re-downloads if it ever needs them again.",
            running_check: None,
            method: Recursive,
        },
        // ================================================================
        // PROJECT BUILD ARTIFACTS
        // ================================================================
        // node_modules + build artifacts are scanned across the common dev-root
        // folders. Non-existent roots resolve to nothing and cost ~zero.
        CacheCategory {
            id: "node-modules",
            label: "node_modules across all projects",
            tier: 1,
            paths: &[
                "Code/**/node_modules",
                "code/**/node_modules",
                "Projects/**/node_modules",
                "projects/**/node_modules",
                "Developer/**/node_modules",
                "dev/**/node_modules",
                "src/**/node_modules",
                "repos/**/node_modules",
                "work/**/node_modules",
                "git/**/node_modules",
                "github/**/node_modules",
                "Sites/**/node_modules",
                "Documents/**/node_modules",
                "Desktop/**/node_modules",
            ],
            max_depth: Some(8),
            why: "400–1100 MB per project. Git worktrees duplicate them.",
            regenerates: "Run `pnpm install` or `npm install` per project to restore.",
            running_check: None,
            method: TrashAll,
        },
        CacheCategory {
            id: "project-build-artifacts",
            label: "Project build artifacts (.next, dist, target, .venv…)",
            tier: 2,
            paths: &[
                "Code/**/.next",
                "Code/**/dist",
                "Code/**/target",
                "Code/**/.venv",
                "Code/**/.turbo",
                "code/**/.next",
                "code/**/dist",
                "code/**/target",
                "Projects/**/.next",
                "Projects/**/dist",
                "Projects/**/target",
                "Projects/**/.venv",
                "projects/**/.next",
                "projects/**/dist",
                "projects/**/target",
                "Developer/**/.next",
                "Developer/**/dist",
                "Developer/**/target",
                "dev/**/.next",
                "dev/**/dist",
                "dev/**/target",
                "src/**/.next",
                "src/**/dist",
                "src/**/target",
                "repos/**/.next",
                "repos/**/dist",
                "repos/**/target",
            ],
            max_depth: Some(8),
            why: "Compiled output — Next.js .next, Vite dist, Rust target, Python .venv — across every project.",
            regenerates: "Rebuilt on the next `build` / `dev` run in each project.",
            running_check: None,
            method: TrashAll,
        },
        // ================================================================
        // SYSTEM / MISC — Tier 1
        // ================================================================
        CacheCategory {
            id: "user-logs",
            label: "User logs (CreativeCloud, Adobe, Claude, NGL…)",
            tier: 1,
            paths: &["Library/Logs"],
            max_depth: Some(2),
            why: "App debug logs you almost never read.",
            regenerates: "Apps write new logs as needed.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "diagnostic-reports",
            label: "Crash & diagnostic reports",
            tier: 1,
            paths: &["Library/Logs/DiagnosticReports"],
            max_depth: None,
            why: "macOS crash reports and spin/hang diagnostics.",
            regenerates: "macOS writes new ones only when something crashes.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "incomplete-downloads",
            label: "Incomplete / interrupted downloads",
            tier: 1,
            paths: &[
                "Downloads/*.download",
                "Downloads/*.crdownload",
                "Downloads/*.part",
            ],
            max_depth: Some(1),
            why: "Partially-downloaded files abandoned by the browser.",
            regenerates: "Nothing to regenerate — these are dead transfers.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "saved-app-state",
            label: "Saved application state",
            tier: 1,
            paths: &["Library/Saved Application State"],
            max_depth: None,
            why: "Per-app window/state snapshots macOS keeps to reopen apps where you left off.",
            regenerates: "Apps just reopen with default windows; rebuilt on next quit.",
            running_check: None,
            method: Recursive,
        },
        CacheCategory {
            id: "trash",
            label: "Empty Trash",
            tier: 1,
            paths: &[".Trash"],
            max_depth: Some(1),
            why: "The Trash itself.",
            regenerates: "—",
            running_check: None,
            method: Recursive,
        },
    ]
});
